### ISSUE TITLE
Vue Support

### ISSUE THREAD

**Issue by christian-thomas** [Rias500/laravel-mix-eslint#1]
At the moment the linter hasn't got support for Vue files.

It's fairly easy to add with:

`test: /\.(js|vue)$/,`

But will also require `eslint-plugin-vue`, and extending the ruleset in your eslint:

```
"extends": [
    "plugin:vue/recommended"
],
```

Is this something you'd look at adding if I update the Readme and PR? If you want me to make the Vue Support optional, I'm happy to add notes to this effect, and make the webpack rule/test customisable under the existing `options` config.

**Comment by Rias500** [comment]
I'll gladly merge a PR for this! I don't think it has to be optional as long as it still works when you're not using Vue.

**Comment by christian-thomas** [comment]
No problem, I'll get a PR in asap. 👍
