### ISSUE TITLE
Module build failed: Error: No ESLint configuration found.

### ISSUE THREAD

**Issue by cyberbit** [Rias500/laravel-mix-eslint#3]
Disclaimer, I'm fairly new to webpack. Here's my `webpack.mix.js` file:

```js
const mix = require('laravel-mix');

require('laravel-mix-eslint');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.js('resources/js/app.js', 'public/js').eslint()
   .sass('resources/sass/app.scss', 'public/css');
```

If using this plugin requires an `.eslintrc.js` file or similar, that should probably be in the readme IMO. ;)

**Comment by Rias500** [comment]
This is just a wrapper around eslint to make it easier to use with Mix, of course you still have to comply to Eslint's requirements https://eslint.org/docs/user-guide/getting-started#configuration

**Comment by cyberbit** [comment]
That's what I figured. Thanks for the help, it's working great now 👍
